apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: component-mgr
  name: component-mgr
spec:
  ports:
  - name: "9004"
    port: 9004
    targetPort: 9004
  selector:
    io.kompose.service: component-mgr
status:
  loadBalancer: {}
