apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: nav
  name: nav
spec:
  ports:
  - name: "9007"
    port: 9007
    targetPort: 9007
  selector:
    io.kompose.service: nav
status:
  loadBalancer: {}
