apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: physics
  name: physics
spec:
  ports:
  - name: "9005"
    port: 9005
    targetPort: 9005
  selector:
    io.kompose.service: physics
status:
  loadBalancer: {}
