apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: radar
  name: radar
spec:
  ports:
  - name: "9006"
    port: 9006
    targetPort: 9006
  selector:
    io.kompose.service: radar
status:
  loadBalancer: {}
