apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: redis
  name: redis
spec:
  ports:
  - name: "6380"
    port: 6380
    targetPort: 6379
  selector:
    io.kompose.service: redis
status:
  loadBalancer: {}
