apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: shard-mgr
  name: shard-mgr
spec:
  ports:
  - name: "9003"
    port: 9003
    targetPort: 9003
  selector:
    io.kompose.service: shard-mgr
status:
  loadBalancer: {}
