apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: system-mgr
  name: system-mgr
spec:
  ports:
  - name: "9002"
    port: 9002
    targetPort: 9002
  selector:
    io.kompose.service: system-mgr
status:
  loadBalancer: {}
