apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: resgate
  name: resgate
spec:
  ports:
  - name: "8080"
    port: 8080
    targetPort: 8080
  selector:
    app: resgate
status:
  loadBalancer: {}
